CONFIG_ADC=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_DYA_ANALOG_INPUT=y
CONFIG_DYA_ANALOG_INPUT_LOG_DBG_RAW=y
CONFIG_DYA_ANALOG_INPUT_LOG_DBG_REPORT=y
CONFIG_ZMK_STUDIO=y
CONFIG_DYA_ANALOG_INPUT_STUDIO_RPC=y
